#!/usr/bin/env node
// Generates supabase/migrations/142_hinterland_water_seed.sql from the reviewed
// register extract (water_register_parsed.json). Idempotent, self-contained
// statements (no temp tables) so it applies cleanly whether or not the runner
// wraps it in a transaction.
//
//   node scripts/hinterland/generate-seed.js
//
// The JSON is the source of truth: `coverage` is already 0..100 (do NOT rescale),
// `status` is already the module's water vocabulary. We only map source_type /
// source_status to option values, fix the register's "Driled/drilled well" typos,
// and parse the messy production/pressure strings to a numeric + kept raw.

const fs = require('fs');
const path = require('path');
const { SHEET, IMPORT_REASON, mapSourceType, mapSourceStatus, parseNum, rawOrNull } = require('./mapping');

const data = require(path.join(__dirname, 'water_register_parsed.json'));

// -- SQL literal helpers ------------------------------------------------------

const q = (v) => (v == null || v === '' ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (v == null || Number.isNaN(v) ? 'NULL' : String(v));

// -- build VALUES tuples ------------------------------------------------------

const communityRows = data.communities.map((c) =>
  `  (${q(c.name)}, ${n(c.region)}, ${q(c.sub)}, ${n(c.pop)}, ${q(SHEET)})`,
);

const waterStatusRows = data.communities.map((c) =>
  `  (${n(c.region)}, ${q(c.name)}, ${q(c.status)}, ${n(c.coverage)}, ${q(c.infra)}, ${q(c.solutions)}, ${q(c.remarks)}, ${q(c.action)}, ${q(c.schools)})`,
);

// Distinct (region, community) for the source delete-then-insert scope.
const srcCommunitySet = new Map();
data.sources.forEach((s) => {
  const key = `${s.region}|${String(s.community).trim().toLowerCase()}`;
  if (!srcCommunitySet.has(key)) srcCommunitySet.set(key, { region: s.region, community: s.community });
});
const sourceCommunityRows = [...srcCommunitySet.values()].map(
  (v) => `  (${n(v.region)}, ${q(v.community)})`,
);

const sourceRows = data.sources.map((s) => {
  const prodNum = parseNum(s.production);
  const presNum = parseNum(s.pressure);
  return `  (${n(s.region)}, ${q(s.community)}, ${q(s.source_name)}, ${q(mapSourceType(s.source_type))}, ${q(mapSourceStatus(s.source_status))}, ${n(prodNum)}, ${q(rawOrNull(s.production))}, ${n(presNum)}, ${q(rawOrNull(s.pressure))})`;
});

// -- assemble SQL -------------------------------------------------------------

const sql = `-- 142_hinterland_water_seed.sql
--
-- Seed the Hinterland Communities water register from the reviewed extract
-- scripts/hinterland/water_register_parsed.json (${data.communities.length} communities, ${data.sources.length} sources — all
-- from Region 9, the only sheet with source-level detail). Generated by
-- scripts/hinterland/generate-seed.js — edit the JSON + regenerate, not this file.
--
-- Idempotent: communities upsert on (region, lower(name)); water_status upserts
-- on community_id; the baseline status log is guarded; water_sources are
-- delete-then-insert scoped to the imported (Region 9) communities.
-- Additive only. coverage is already 0..100 (not rescaled). nearest_airstrip_id
-- is intentionally left untouched (airstrip links are set manually).

-- 1. Communities ------------------------------------------------------------
INSERT INTO public.communities (name, region, sub_district, population, source_sheet)
VALUES
${communityRows.join(',\n')}
ON CONFLICT (region, lower(name)) DO UPDATE SET
  sub_district = EXCLUDED.sub_district,
  population   = EXCLUDED.population,
  source_sheet = EXCLUDED.source_sheet,
  updated_at   = now();

-- 2. Water status (1:1) -----------------------------------------------------
INSERT INTO public.water_status
  (community_id, status, coverage_percent, existing_infrastructure, proposed_solutions, remarks, action, schools_access, source_sheet)
SELECT c.id, v.status, v.coverage::numeric, v.infra, v.solutions, v.remarks, v.action, v.schools, ${q(SHEET)}
FROM (VALUES
${waterStatusRows.join(',\n')}
) AS v(region, name, status, coverage, infra, solutions, remarks, action, schools)
JOIN public.communities c ON c.region = v.region AND lower(c.name) = lower(v.name)
ON CONFLICT (community_id) DO UPDATE SET
  status                  = EXCLUDED.status,
  coverage_percent        = EXCLUDED.coverage_percent,
  existing_infrastructure = EXCLUDED.existing_infrastructure,
  proposed_solutions      = EXCLUDED.proposed_solutions,
  remarks                 = EXCLUDED.remarks,
  action                  = EXCLUDED.action,
  schools_access          = EXCLUDED.schools_access,
  source_sheet            = EXCLUDED.source_sheet,
  updated_at              = now();

-- 3. Baseline status log (one row per imported community; guarded) ----------
INSERT INTO public.water_status_log (community_id, previous_status, new_status, reason)
SELECT ws.community_id, NULL, ws.status, ${q(IMPORT_REASON)}
FROM public.water_status ws
JOIN public.communities c ON c.id = ws.community_id
WHERE c.source_sheet = ${q(SHEET)}
  AND NOT EXISTS (
    SELECT 1 FROM public.water_status_log l
    WHERE l.community_id = ws.community_id AND l.reason = ${q(IMPORT_REASON)}
  );

-- 4. Water sources (Region 9) — delete-then-insert for a clean reseed -------
DELETE FROM public.water_sources ws
WHERE ws.community_id IN (
  SELECT c.id FROM public.communities c
  JOIN (VALUES
${sourceCommunityRows.join(',\n')}
  ) AS v(region, community) ON c.region = v.region AND lower(c.name) = lower(v.community)
);

INSERT INTO public.water_sources
  (community_id, source_name, source_type, source_status, production_m3hr, production_raw, pressure_psi, pressure_raw)
SELECT c.id, v.source_name, v.source_type, v.source_status, v.production_m3hr::numeric, v.production_raw, v.pressure_psi::numeric, v.pressure_raw
FROM (VALUES
${sourceRows.join(',\n')}
) AS v(region, community, source_name, source_type, source_status, production_m3hr, production_raw, pressure_psi, pressure_raw)
JOIN public.communities c ON c.region = v.region AND lower(c.name) = lower(v.community);
`;

const outPath = path.join(__dirname, '..', '..', 'supabase', 'migrations', '142_hinterland_water_seed.sql');
fs.writeFileSync(outPath, sql);

console.log(`Wrote ${outPath}`);
console.log(`  communities:   ${communityRows.length}`);
console.log(`  water_status:  ${waterStatusRows.length}`);
console.log(`  water_sources: ${sourceRows.length} (across ${sourceCommunityRows.length} Region 9 communities)`);
console.log(`  SQL size:      ${(sql.length / 1024).toFixed(1)} KB`);
