'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import Link from 'next/link';
import {
  X, ArrowLeft, MessageSquare,
  Send, FileText, ArrowRight,
} from 'lucide-react';
import { formatDistanceToNow, format, parseISO, differenceInDays } from 'date-fns';
import { Spinner } from '@/components/ui/Spinner';
import { useToast } from '@/components/ui/Toast';

interface ApplicationDetail {
  id: string;
  agency: string;
  applicant_name: string;
  application_type: string;
  reference_number: string | null;
  status: string;
  priority: string;
  submitted_at: string;
  notes: string | null;
  created_at: string;
}

interface Note {
  id: string;
  note_text: string;
  status_at_time: string | null;
  new_status: string | null;
  author_name: string | null;
  created_by: string;
  created_at: string;
}

interface ActivityEntry {
  id: string;
  action: string;
  old_value: string | null;
  new_value: string | null;
  performer_name: string | null;
  performed_at: string;
  details: Record<string, unknown> | null;
}

type TimelineItem =
  | { type: 'note'; data: Note }
  | { type: 'activity'; data: ActivityEntry };

const STATUS_STYLES: Record<string, { bg: string; label: string }> = {
  pending: { bg: 'bg-amber-500/20 text-amber-400', label: 'Pending' },
  under_review: { bg: 'bg-blue-500/20 text-blue-400', label: 'Under Review' },
  approved: { bg: 'bg-green-500/20 text-green-400', label: 'Approved' },
  rejected: { bg: 'bg-red-500/20 text-red-400', label: 'Rejected' },
};

const STATUS_OPTIONS = [
  { value: 'pending', label: 'Pending' },
  { value: 'under_review', label: 'Under Review' },
  { value: 'approved', label: 'Approved' },
  { value: 'rejected', label: 'Rejected' },
];

interface Props {
  applicationId: string | null;
  isOpen: boolean;
  onClose: () => void;
  onStatusChange?: () => void;
}

export function ApplicationDetailDrawer({ applicationId, isOpen, onClose, onStatusChange }: Props) {
  const { toast } = useToast();
  const [app, setApp] = useState<ApplicationDetail | null>(null);
  const [notes, setNotes] = useState<Note[]>([]);
  const [activity, setActivity] = useState<ActivityEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [noteText, setNoteText] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const fetchData = useCallback(async () => {
    if (!applicationId) return;
    setLoading(true);
    try {
      const [appRes, notesRes] = await Promise.all([
        fetch(`/api/applications/${applicationId}`),
        fetch(`/api/applications/${applicationId}/notes`),
      ]);

      if (appRes.ok) {
        const appData = await appRes.json();
        setApp(appData.application);
        setActivity(appData.activity || []);
        setSelectedStatus(appData.application?.status || '');
      }

      if (notesRes.ok) {
        const notesData = await notesRes.json();
        setNotes(notesData.notes || []);
      }
    } catch { /* handled by empty state */ }
    setLoading(false);
  }, [applicationId]);

  useEffect(() => {
    if (isOpen && applicationId) {
      fetchData();
      setNoteText('');
    }
  }, [isOpen, applicationId, fetchData]);

  // Escape key
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) onClose();
    };
    window.addEventListener('keydown', handleEscape);
    return () => window.removeEventListener('keydown', handleEscape);
  }, [isOpen, onClose]);

  // Body scroll lock
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);

  const handleSubmitNote = async () => {
    if (!noteText.trim() || !applicationId) return;
    setSubmitting(true);

    const body: Record<string, string> = { note_text: noteText.trim() };
    if (selectedStatus && selectedStatus !== app?.status) {
      body.new_status = selectedStatus;
    }

    try {
      const res = await fetch(`/api/applications/${applicationId}/notes`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      if (res.ok) {
        toast.success('Note added');
        setNoteText('');
        fetchData();
        onStatusChange?.();
      } else {
        const data = await res.json();
        toast.error(data.error || 'Failed to add note');
      }
    } catch {
      toast.error('Failed to add note');
    }
    setSubmitting(false);
  };

  // Build merged timeline: notes + activity (excluding activity entries generated by notes)
  const timeline = useMemo(() => {
    const items: TimelineItem[] = [];
    for (const n of notes) {
      items.push({ type: 'note', data: n });
    }
    for (const a of activity) {
      if (a.details && (a.details as Record<string, unknown>).from_note) continue;
      items.push({ type: 'activity', data: a });
    }
    items.sort((a, b) => {
      const ta = a.type === 'note' ? a.data.created_at : a.data.performed_at;
      const tb = b.type === 'note' ? b.data.created_at : b.data.performed_at;
      return new Date(tb).getTime() - new Date(ta).getTime();
    });
    return items;
  }, [notes, activity]);

  const daysPending = app ? differenceInDays(new Date(), parseISO(app.submitted_at)) : 0;

  return (
    <>
      {/* Backdrop */}
      <div
        className={`fixed inset-0 bg-black/50 backdrop-blur-sm z-[46] transition-opacity duration-300 ${
          isOpen ? 'opacity-100' : 'opacity-0 pointer-events-none'
        }`}
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Panel */}
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Application details"
        className={`fixed inset-y-0 right-0 w-full sm:w-[600px] lg:w-[700px] bg-navy-950 border-l border-navy-800 z-50 flex flex-col transform transition-transform duration-300 ease-out ${
          isOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        {loading ? (
          <div className="flex-1 p-6 space-y-4 animate-pulse">
            <div className="h-6 bg-navy-800 rounded w-2/3" />
            <div className="h-4 bg-navy-800 rounded w-1/3" />
            <div className="flex gap-2">
              <div className="h-6 bg-navy-800 rounded w-20" />
              <div className="h-6 bg-navy-800 rounded w-16" />
            </div>
            <div className="h-px bg-navy-800 mt-4" />
            <div className="h-20 bg-navy-800 rounded" />
            <div className="h-px bg-navy-800" />
            <div className="space-y-3">
              <div className="h-16 bg-navy-800 rounded" />
              <div className="h-16 bg-navy-800 rounded" />
              <div className="h-16 bg-navy-800 rounded" />
            </div>
          </div>
        ) : !app ? (
          <div className="flex-1 flex items-center justify-center">
            <p className="text-navy-600 text-sm">Application not found</p>
          </div>
        ) : (
          <>
            {/* Drawer Header */}
            <div className="flex-shrink-0 bg-navy-900/95 backdrop-blur-sm border-b border-navy-800 px-4 md:px-6 py-3 md:py-4">
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-3 mb-1">
                    <button
                      onClick={onClose}
                      className="p-2 -ml-2 rounded-lg hover:bg-navy-800 text-slate-400 hover:text-white transition-colors lg:hidden"
                      aria-label="Close"
                    >
                      <ArrowLeft size={20} />
                    </button>
                    <h2 className="text-xl font-bold text-white truncate">{app.applicant_name}</h2>
                  </div>
                  <div className="flex items-center flex-wrap gap-2 mt-1">
                    {app.reference_number && (
                      <span className="text-xs font-mono text-gold-500">{app.reference_number}</span>
                    )}
                    <span className={`text-[10px] px-2 py-0.5 rounded-full font-medium ${STATUS_STYLES[app.status]?.bg || ''}`}>
                      {STATUS_STYLES[app.status]?.label || app.status}
                    </span>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-navy-800 text-slate-400 font-medium">
                      {app.agency.toUpperCase()}
                    </span>
                  </div>
                  <div className="flex items-center flex-wrap gap-x-2 gap-y-0.5 mt-1.5 text-xs text-navy-600">
                    <span>{app.application_type}</span>
                    <span>&middot;</span>
                    <span>{format(parseISO(app.submitted_at), 'MMM d, yyyy')}</span>
                    <span>&middot;</span>
                    <span className={daysPending > 30 ? 'text-amber-400' : ''}>
                      {daysPending} day{daysPending !== 1 ? 's' : ''} pending
                    </span>
                  </div>
                </div>
                <button
                  onClick={onClose}
                  className="hidden lg:flex p-2 rounded-lg hover:bg-navy-800 text-slate-400 hover:text-white transition-colors shrink-0"
                  aria-label="Close"
                >
                  <X size={20} />
                </button>
              </div>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 min-h-0 overflow-y-auto p-4 md:p-6 space-y-5" style={{ WebkitOverflowScrolling: 'touch' }}>
              {/* Add Note */}
              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-white flex items-center gap-2">
                  <MessageSquare className="h-4 w-4 text-gold-500" />
                  Add Note
                </h3>
                <textarea
                  value={noteText}
                  onChange={e => setNoteText(e.target.value)}
                  placeholder="Add a note about this application..."
                  rows={3}
                  className="w-full px-3 py-2.5 bg-navy-950 border border-navy-800 rounded-lg text-sm text-white placeholder:text-navy-600 focus:outline-none focus:ring-1 focus:ring-gold-500/50 resize-none"
                />
                <div className="flex items-center gap-3">
                  <div className="flex-1">
                    <select
                      value={selectedStatus}
                      onChange={e => setSelectedStatus(e.target.value)}
                      className="w-full px-3 py-2 bg-navy-950 border border-navy-800 rounded-lg text-xs text-white focus:outline-none focus:ring-1 focus:ring-gold-500/50"
                    >
                      {STATUS_OPTIONS.map(s => (
                        <option key={s.value} value={s.value}>
                          {s.label}{s.value === app.status ? ' (current)' : ''}
                        </option>
                      ))}
                    </select>
                  </div>
                  <button
                    onClick={handleSubmitNote}
                    disabled={submitting || !noteText.trim()}
                    className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gold-500 text-navy-950 text-xs font-semibold hover:bg-[#e5c348] disabled:opacity-50 transition-colors shrink-0"
                  >
                    {submitting ? (
                      <Spinner size="sm" className="border-navy-950 border-t-transparent" />
                    ) : (
                      <Send className="h-3.5 w-3.5" />
                    )}
                    {submitting ? 'Saving...' : 'Add Note'}
                  </button>
                </div>
                {selectedStatus && selectedStatus !== app.status && (
                  <p className="text-[10px] text-amber-400">
                    Status will change: {STATUS_STYLES[app.status]?.label} &rarr; {STATUS_STYLES[selectedStatus]?.label}
                  </p>
                )}
              </div>

              {/* Divider */}
              <div className="border-t border-navy-800" />

              {/* Timeline */}
              <div>
                <h3 className="text-sm font-semibold text-white mb-4">Timeline</h3>
                {timeline.length === 0 ? (
                  <div className="text-center py-8">
                    <MessageSquare className="h-8 w-8 text-navy-700 mx-auto mb-2" />
                    <p className="text-sm text-navy-600">No notes yet.</p>
                    <p className="text-xs text-navy-700 mt-1">Add the first note to track this application&apos;s progress.</p>
                  </div>
                ) : (
                  <div className="space-y-0">
                    {timeline.map((item, i) => {
                      if (item.type === 'note') {
                        const n = item.data;
                        const initial = n.author_name?.[0]?.toUpperCase() || '?';
                        return (
                          <div key={`note-${n.id}`} className="relative pl-10 pb-5 last:pb-0">
                            {i < timeline.length - 1 && (
                              <div className="absolute left-[15px] top-8 bottom-0 w-px bg-navy-800" />
                            )}
                            <div className="absolute left-0 top-0 w-8 h-8 rounded-full bg-gold-500/20 border border-gold-500/30 flex items-center justify-center text-xs font-bold text-gold-500">
                              {initial}
                            </div>
                            <div>
                              <div className="flex items-center gap-2 mb-1">
                                <span className="text-xs font-medium text-white">{n.author_name || 'Unknown'}</span>
                                <span
                                  className="text-[10px] text-navy-600"
                                  title={format(parseISO(n.created_at), 'PPpp')}
                                >
                                  {formatDistanceToNow(parseISO(n.created_at), { addSuffix: true })}
                                </span>
                              </div>
                              <p className="text-sm text-slate-300 whitespace-pre-wrap">{n.note_text}</p>
                              {n.new_status && (
                                <div className="flex items-center gap-1.5 mt-2">
                                  <span className={`text-[10px] px-1.5 py-0.5 rounded ${STATUS_STYLES[n.status_at_time || '']?.bg || 'bg-navy-800 text-slate-400'}`}>
                                    {STATUS_STYLES[n.status_at_time || '']?.label || n.status_at_time}
                                  </span>
                                  <ArrowRight className="h-3 w-3 text-navy-600" />
                                  <span className={`text-[10px] px-1.5 py-0.5 rounded ${STATUS_STYLES[n.new_status]?.bg || ''}`}>
                                    {STATUS_STYLES[n.new_status]?.label || n.new_status}
                                  </span>
                                </div>
                              )}
                            </div>
                          </div>
                        );
                      }

                      // System activity entry — lighter treatment
                      const a = item.data;
                      return (
                        <div key={`activity-${a.id}`} className="relative pl-10 pb-4 last:pb-0">
                          {i < timeline.length - 1 && (
                            <div className="absolute left-[15px] top-6 bottom-0 w-px bg-navy-800" />
                          )}
                          <div className={`absolute left-[5px] top-1 w-5 h-5 rounded-full flex items-center justify-center ${
                            a.action === 'status_changed'
                              ? 'bg-gold-500/10 border border-gold-500/30'
                              : a.action === 'document_uploaded'
                              ? 'bg-blue-400/10 border border-blue-400/30'
                              : a.action === 'document_deleted'
                              ? 'bg-red-400/10 border border-red-400/30'
                              : 'bg-navy-800 border border-navy-700'
                          }`}>
                            <div className={`w-1.5 h-1.5 rounded-full ${
                              a.action === 'status_changed' ? 'bg-gold-500'
                              : a.action === 'document_uploaded' ? 'bg-blue-400'
                              : a.action === 'document_deleted' ? 'bg-red-400'
                              : 'bg-navy-600'
                            }`} />
                          </div>
                          <div>
                            <p className="text-[11px] text-navy-600">
                              <span className="text-slate-400">{a.performer_name || 'System'}</span>{' '}
                              {a.action === 'created' ? 'created this application'
                                : a.action === 'status_changed' ? 'changed status'
                                : a.action === 'document_uploaded' ? 'uploaded a document'
                                : a.action === 'document_deleted' ? 'deleted a document'
                                : a.action}
                            </p>
                            {a.action === 'status_changed' && a.old_value && a.new_value && (
                              <div className="flex items-center gap-1 mt-0.5">
                                <span className={`text-[9px] px-1 py-0.5 rounded ${STATUS_STYLES[a.old_value]?.bg || ''}`}>
                                  {STATUS_STYLES[a.old_value]?.label || a.old_value}
                                </span>
                                <ArrowRight className="h-2.5 w-2.5 text-navy-700" />
                                <span className={`text-[9px] px-1 py-0.5 rounded ${STATUS_STYLES[a.new_value]?.bg || ''}`}>
                                  {STATUS_STYLES[a.new_value]?.label || a.new_value}
                                </span>
                              </div>
                            )}
                            {a.action === 'document_uploaded' && a.new_value && (
                              <p className="text-[10px] text-navy-700 mt-0.5 truncate">{a.new_value}</p>
                            )}
                            {a.action === 'status_changed' && typeof a.details?.note === 'string' && (
                              <p className="text-[10px] text-navy-600 mt-0.5 italic">&ldquo;{a.details.note}&rdquo;</p>
                            )}
                            <p className="text-[10px] text-navy-700 mt-0.5">
                              {formatDistanceToNow(parseISO(a.performed_at), { addSuffix: true })}
                            </p>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
            </div>

            {/* Footer */}
            <div className="flex-shrink-0 border-t border-navy-800 px-4 md:px-6 py-3 flex items-center justify-between bg-navy-900/95">
              <Link
                href={`/applications/${app.id}`}
                className="flex items-center gap-2 text-xs text-gold-500 hover:text-[#e5c348] transition-colors"
                onClick={onClose}
              >
                <FileText className="h-3.5 w-3.5" />
                View Full Details &amp; Documents
              </Link>
              <button
                onClick={onClose}
                className="px-4 py-2 text-xs text-slate-400 hover:text-white border border-navy-800 rounded-lg hover:border-navy-700 transition-colors"
              >
                Close
              </button>
            </div>
          </>
        )}

      </div>
    </>
  );
}
